name: doc_doc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.4
  # Code Generator for Cubit and Retrofit
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  # for Localization
  intl: ^0.18.1
  easy_localization: ^3.0.0
  # for splash screen
  flutter_native_splash: ^2.3.13
  # An SVG rendering and widget library for Flutter
  flutter_svg: ^2.0.10+1
  # A flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:

  uses-material-design: true

  assets:
    -  assets/images/
    -  assets/fonts/
    -  assets/svgs/
